import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { compileWorld } from "../packages/compiler/dist/index.js";
import { compareStableStrings } from "./stable-order.mts";

interface PackageManifest {
  readonly name: string;
  readonly version: string;
  readonly description: string;
  readonly license: string;
  readonly keywords?: readonly string[];
  readonly maintainers?: readonly { readonly name: string }[];
  readonly firedrill?: {
    readonly layer?: string;
    readonly tool?: string;
    readonly lifecycle?: "active" | "deprecated" | "revoked";
    readonly conformance?: string;
  };
}

interface RegistryEntry {
  readonly packageName: string;
  readonly packageVersion: string;
  readonly description: string;
  readonly license: string;
  readonly lifecycle: "active" | "deprecated";
  readonly maintainers: readonly string[];
  readonly keywords: readonly string[];
  readonly conformanceSuite: string;
  readonly tool: {
    readonly id: string;
    readonly version: string;
    readonly engine: string;
    readonly capabilities: readonly string[];
    readonly state: readonly string[];
    readonly operations: readonly {
      readonly id: string;
      readonly fidelity: string;
    }[];
    readonly events: readonly string[];
    readonly faults: readonly string[];
    readonly subscriptions: readonly string[];
  };
}

interface RegistryRecord {
  readonly directoryName: string;
  readonly entry: RegistryEntry;
}

const root = resolve(import.meta.dirname, "..");
const packsRoot = join(root, "tool-packs");
const registryRoot = join(root, "registry");
const jsonOutputPath = join(registryRoot, "index.json");
const markdownOutputPath = join(registryRoot, "README.md");
const records: RegistryRecord[] = [];

function inlineList(values: readonly string[]): string {
  return values.length === 0 ? "None" : values.map((value) => `\`${value}\``).join(", ");
}

function renderMarkdown(entries: readonly RegistryRecord[]): string {
  const lines = [
    "# Reusable Tool packs",
    "",
    "> Generated by `pnpm registry:write`. Do not edit this file by hand.",
    "",
    "A Tool pack adds a reusable action surface to a Firedrill world. This catalog helps humans and coding agents discover packs; it does not install or activate them. A pack runs only after it is installed and explicitly selected in `firedrill.json`. Firedrill validates the exact installed artifact and can then run it offline.",
    "",
    "Package-manager availability depends on each pack's release status. Follow the linked pack documentation instead of assuming every catalog entry has been published.",
    "",
  ];

  if (entries.length === 0) {
    lines.push("No reusable Tool packs are cataloged yet.", "");
    return `${lines.join("\n").trimEnd()}\n`;
  }

  for (const record of entries) {
    const { entry } = record;
    lines.push(
      `## [\`${entry.packageName}\`](../tool-packs/${record.directoryName}/README.md)`,
      "",
      entry.description,
      "",
      `- Version: \`${entry.packageVersion}\``,
      `- Tool ID: \`${entry.tool.id}\``,
      `- Lifecycle: \`${entry.lifecycle}\``,
      `- License: \`${entry.license}\``,
      `- Engine compatibility: \`${entry.tool.engine}\``,
      `- Capabilities: ${inlineList(entry.tool.capabilities)}`,
      `- State namespaces: ${inlineList(entry.tool.state)}`,
      `- Events: ${inlineList(entry.tool.events)}`,
      `- Faults: ${inlineList(entry.tool.faults)}`,
      `- Subscriptions: ${inlineList(entry.tool.subscriptions)}`,
      "",
      "Operations:",
      "",
      ...entry.tool.operations.map((operation) => `- \`${operation.id}\` — ${operation.fidelity} fidelity`),
      "",
    );
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

for (const entry of readdirSync(packsRoot, { withFileTypes: true }).sort((left, right) =>
  compareStableStrings(left.name, right.name),
)) {
  if (!entry.isDirectory()) continue;
  const directory = join(packsRoot, entry.name);
  let package_: PackageManifest;
  try {
    package_ = JSON.parse(readFileSync(join(directory, "package.json"), "utf8")) as PackageManifest;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
    throw error;
  }
  if (package_.firedrill?.layer !== "tool-pack") continue;
  if (!package_.firedrill.tool || !package_.firedrill.lifecycle || !package_.firedrill.conformance) {
    throw new Error(`${package_.name} must declare firedrill.tool, lifecycle, and conformance`);
  }
  if (package_.firedrill.lifecycle === "revoked") {
    throw new Error(
      `${package_.name}@${package_.version} is revoked and cannot appear in the generated catalog`,
    );
  }
  const compiled = await compileWorld({ repositoryRoot: directory, materialize: false });
  if (compiled.status === "failed") {
    throw new Error(`${package_.name} does not compile\n${JSON.stringify(compiled.diagnostics, null, 2)}`);
  }
  if (compiled.build.worldIr.tools.length !== 1) {
    throw new Error(`${package_.name} must compile exactly one Tool manifest`);
  }
  const tool = compiled.build.worldIr.tools[0];
  if (tool === undefined) throw new Error(`${package_.name} compiled no Tool`);
  if (tool.version !== package_.version) {
    throw new Error(`${package_.name} package version ${package_.version} differs from Tool ${tool.version}`);
  }
  if (!compiled.build.worldIr.suites.some((suite) => suite.id === package_.firedrill?.conformance)) {
    throw new Error(`${package_.name} has no declared conformance suite ${package_.firedrill.conformance}`);
  }
  records.push({
    directoryName: entry.name,
    entry: {
      packageName: package_.name,
      packageVersion: package_.version,
      description: package_.description,
      license: package_.license,
      lifecycle: package_.firedrill.lifecycle,
      maintainers: (package_.maintainers ?? []).map((maintainer) => maintainer.name),
      keywords: [...(package_.keywords ?? [])].sort(compareStableStrings),
      conformanceSuite: package_.firedrill.conformance,
      tool: {
        id: tool.id,
        version: tool.version,
        engine: tool.engine,
        capabilities: tool.capabilities,
        state: tool.state.map((state) => state.namespace),
        operations: tool.operations.map((operation) => ({
          id: operation.id,
          fidelity: operation.fidelity,
        })),
        events: tool.events.map((event) => event.id),
        faults: tool.faults.map((fault) => fault.id),
        subscriptions: tool.subscriptions.map((subscription) => subscription.id),
      },
    },
  });
}

const unformatted = `${JSON.stringify(
  { schemaVersion: 1, packages: records.map((record) => record.entry) },
  null,
  2,
)}\n`;
const formatted = spawnSync("pnpm", ["exec", "biome", "format", "--stdin-file-path", jsonOutputPath], {
  cwd: root,
  encoding: "utf8",
  input: unformatted,
  stdio: ["pipe", "pipe", "pipe"],
});
if (formatted.status !== 0) {
  throw new Error(`cannot format generated registry metadata\n${formatted.stderr}`);
}
const jsonOutput = formatted.stdout;
const markdownOutput = renderMarkdown(records);
if (process.argv.includes("--check")) {
  const stale: string[] = [];
  for (const [path, output] of [
    [jsonOutputPath, jsonOutput],
    [markdownOutputPath, markdownOutput],
  ] as const) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    if (current !== output) stale.push(path.slice(root.length + 1));
  }
  if (stale.length > 0) {
    process.stderr.write(`${stale.join(", ")} stale; run pnpm registry:write\n`);
    process.exit(1);
  }
} else {
  mkdirSync(registryRoot, { recursive: true });
  writeFileSync(jsonOutputPath, jsonOutput);
  writeFileSync(markdownOutputPath, markdownOutput);
  process.stdout.write(
    `wrote ${records.length} Tool pack record(s) to registry/index.json and registry/README.md\n`,
  );
}
