import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

interface PublicSurface {
  readonly cli: {
    readonly binary: string;
    readonly entrypoint: string;
    readonly helpCommands: readonly (readonly string[])[];
  };
}

const root = resolve(import.meta.dirname, "..");
const outputPath = join(root, "docs", "cli-reference.md");
const publicSurface = JSON.parse(
  readFileSync(join(root, "release", "public-surface.json"), "utf8"),
) as PublicSurface;
const cli = resolve(root, "packages", "cli", publicSurface.cli.entrypoint.replace(/^\.\//, ""));

function renderHelp(arguments_: readonly string[]): string {
  const result = spawnSync(process.execPath, [cli, ...arguments_, "--help"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, CI: "true", NO_COLOR: "1" },
    stdio: "pipe",
  });
  const invocation = [publicSurface.cli.binary, ...arguments_].join(" ");
  if (result.status !== 0 || result.stderr !== "") {
    throw new Error(`${invocation} --help failed\n${result.stdout ?? ""}\n${result.stderr ?? ""}`);
  }
  const help = result.stdout.replace(/\r\n/g, "\n").trimEnd();
  if (!help.includes("Usage:") || !help.includes(publicSurface.cli.binary)) {
    throw new Error(`${invocation} --help did not describe a public CLI invocation`);
  }
  return `## \`${invocation}\`\n\n\`\`\`text\n${help}\n\`\`\``;
}

const commands = publicSurface.cli.helpCommands;
if (commands.length === 0 || commands[0]?.length !== 0) {
  throw new Error("the frozen CLI help surface must begin with the root command");
}

const rendered = `<!-- Generated by tooling/generate-cli-reference.mts. Do not edit by hand. -->

# CLI reference

This reference is generated from the release-candidate CLI itself. It documents local, account-free commands and does not imply that the packages have been published.

${commands.map(renderHelp).join("\n\n")}
`;

if (process.argv.includes("--write")) {
  writeFileSync(outputPath, rendered);
  process.stdout.write(`wrote ${commands.length} CLI help section(s) to docs/cli-reference.md\n`);
} else if (process.argv.includes("--check")) {
  const existing = readFileSync(outputPath, "utf8");
  if (existing !== rendered) {
    throw new Error("docs/cli-reference.md is stale; run pnpm docs:cli:write");
  }
  process.stdout.write(`CLI reference matches ${commands.length} executable help section(s)\n`);
} else {
  process.stderr.write("Usage: tsx tooling/generate-cli-reference.mts <--write|--check>\n");
  process.exitCode = 2;
}
